server:
  port: 8081
spring:
  application:
    name: board
# database ============
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-name
    streams:
      state:
        dir: /Users/mihee/environment/stateDir

# swagger ui ================
springdoc:
  # endpoint 표시 여부
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# 카프카 토픽
message:
  topic:
    name: baeldung
long:
  message:
    topic:
      name: longMessage
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned
multi:
  type:
    topic:
      name: multitype

test:
  topic: test