server:
  port: 8081
spring:
  application:
    name: board
# database ============
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-name
    streams:
      state:
        dir: /Users/mihee/environment/stateDir

# swagger ui ================
springdoc:
  # endpoint 표시 여부
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# 카프카 토픽
message:
  topic:
    name: baeldung
long:
  message:
    topic:
      name: longMessage
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned
multi:
  type:
    topic:
      name: multitype

# 카프카 monitoring
monitor:
  kafka:
    bootstrap:
      config: localhost:8082
    consumer:
      # groupid: baeldungGrp
      groupid:
        simulate: baeldungGrpSimulate
  topic:
    name: baeldung
  producer:
    simulate: true
  consumer:
    simulate: true


#management.endpoints.web.base-path=/actuator
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#management.endpoint.metrics.enabled=true
#management.endpoint.prometheus.enabled=true


test:
  topic: test